### ISSUE TITLE
Static blog site scrolls horizontally

### ISSUE THREAD

**Issue by rreusser** [HappyFunCorp/happy_seed#29]
Investigating the container situation...

**Comment by rreusser** [comment]
.timeline needs:

    .timeline
      @extend .container-fluid;

Reorganizing the CSS as a whole at the moment… it's kinda all jammed into one file. I think it'd benefit a lot from separating out the components so it's not already out of control by the time you start an empty blog site.

**Comment by wschenk** [comment]
Go for it.

-- 
Will Schenk
http://happyfuncorp.com
http://willschenk.com
http://sublimeguile.com

**Comment by rreusser** [comment]
Though, to be clear, I struggle with CSS organization. It's tricky. Like rows and columns should logically be separate from typography styles… I haven't found a convention or way to organize this stuff logically that scales well.

**Comment by wschenk** [comment]
I like to put things in one file and have each block be a different page, but that’s just me. 

-- 
Will Schenk
http://happyfuncorp.com
http://willschenk.com
http://sublimeguile.com
