### ISSUE TITLE
RSpec tests don't run: circular dependency error

### ISSUE THREAD

**Issue by rreusser** [HappyFunCorp/happy_seed#30]
Situation: I create an new rails app with everything except angular
Expected: Tests are runnable
Observed: rspec tests don't run due to circular dependency error

Tried this fix, but to no avail: http://stackoverflow.com/questions/24673301/runtimeerror-circular-dependency-detected-while-autoloading-constant

    $ bundle exec rspec
    DEPRECATION WARNING: The configuration option `config.serve_static_assets` has been renamed to `config.serve_static_files` to clarify its role (it merely enables serving everything in the `public` folder and is unrelated to the asset pipeline). The `serve_static_assets` alias will be removed in Rails 5.0. Please migrate your configuration files accordingly. (called from block in tsort_each at /Users/rreusser/.rvm/rubies/ruby-2.0.0-p481/lib/ruby/2.0.0/tsort.rb:150)
    /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:492:in `load_missing_constant': Circular dependency detected while autoloading constant User (RuntimeError)
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/rreusser/projects/testing/test_test/app/admin/user.rb:1:in `<top (required)>'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/rreusser/projects/testing/test_test/app/models/form_user.rb:1:in `<top (required)>'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:494:in `load_missing_constant'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:184:in `const_missing'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:261:in `const_get'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:261:in `block in constantize'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259:in `each'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259:in `inject'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/inflector/methods.rb:259:in `constantize'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:566:in `get'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:597:in `constantize'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/devise-3.4.0/lib/devise.rb:302:in `get'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/devise-3.4.0/lib/devise/mapping.rb:80:in `to'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/devise-3.4.0/lib/devise/mapping.rb:75:in `modules'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/devise-3.4.0/lib/devise/mapping.rb:92:in `routes'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/devise-3.4.0/lib/devise/mapping.rb:159:in `default_used_route'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/devise-3.4.0/lib/devise/mapping.rb:69:in `initialize'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/devise-3.4.0/lib/devise.rb:336:in `new'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/devise-3.4.0/lib/devise.rb:336:in `add_mapping'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/devise-3.4.0/lib/devise/rails/routes.rb:224:in `block in devise_for'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/devise-3.4.0/lib/devise/rails/routes.rb:223:in `each'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/devise-3.4.0/lib/devise/rails/routes.rb:223:in `devise_for'
	from /Users/rreusser/projects/testing/test_test/config/routes.rb:2:in `block in <top (required)>'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:423:in `instance_exec'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:423:in `eval_block'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/actionpack-4.2.0/lib/action_dispatch/routing/route_set.rb:401:in `draw'
	from /Users/rreusser/projects/testing/test_test/config/routes.rb:1:in `<top (required)>'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/rreusser/.rvm/gems/ruby-2.0.0-p481/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
    ....

**Comment by rreusser** [comment]
Oh. Never mind. Not just tests. The rails app doesn't run at all. Hmmmm.

**Comment by bschippers718** [comment]
Did you try replacing the batteries?  

—  //  —  //  —
Ben Schippers
HappyFunCorp.Com (http://www.happyfuncorp.com)
Building for the future
718.669.0001
Interesting readings:

TechCrunch, Built In Brooklyn (http://techcrunch.com/2015/01/12/built-in-brooklyn-happyfuncorp/)


Brooklyn Magazine/HFC (http://www.bkmag.com/2014/07/15/a-technology-academy-grows-in-brooklyn/)


Fastcompany/HFC (http://www.fastcolabs.com/3033050/why-you-should-learn-product-management-instead-of-coding?partner=rss)





TechCrunch/HFC (http://techcrunch.com/2014/07/13/hfc-academy/)

**Comment by rreusser** [comment]
Haven't tried. Looks like it's something related to active_admin registering the user model. Can't quite figure out what's triggering it or how to avoid it.

**Comment by rreusser** [comment]
Never mind. Looks like it's just a result of activeadmin being left in a half-installed state due to the inherited_resources failure.
