### ISSUE TITLE
bh gem?

### ISSUE THREAD

**Issue by rreusser** [HappyFunCorp/happy_seed#32]
Mixed feelings on including this. Bottom line: it's not apparent to me that the markup can be customized, which seems like it'd severely limit the usefulness on real projects.

Compare this to: http://simple-form-bootstrap.plataformatec.com.br/

I tracked down a config file for simple_form_for + bootstrap that pretty much nails the bootstrap helpers + forms + validations, and it's pretty easy to add in your own (like bootstrap + third-party date selector = date_field).

I realize they don't quite fill the same need; just wary of fully endorsing gems that in reality you'd really just have to work around.

**Comment by wschenk** [comment]
Simple form only does forms though.  What about the rest of it?  Alerts and navs and modals and all that.

Whats the equivalent code for

= form_for @shout, layout: :basic do |f|
  = f.text_field :to, use_label: false, placeholder: "Name or Email”
  = f.submit “Send”




-- 
Will Schenk
http://happyfuncorp.com
http://willschenk.com
http://sublimeguile.com

**Comment by wschenk** [comment]
I'd almost rather create some good helpers for error messages, and let people go custom if that makes more sense.

**Comment by rreusser** [comment]
Yeah, that's why I say it's not really a replacement. But the markup is fully specified in an initializer, and it's easy to add new field types with arbitrarily complex markup and javascript. Handles error messages and has-error classes. The customizable part is a real winner to me.

  = simple_form_for @shout, wrapper: :horizontal_form do |f|
   = f.input :referrer_name
   = f.submit 'Submit'

**Comment by wschenk** [comment]
I don’t have a strong opinion.  I do like having all of the helpers for everything, since it makes it much faster to pump out a site.  If we then need to back peddle a bit to fit the design I think its still ok.

On the otherhand, there’s not reason why you couldn’t use simple_form for the forms and bh for everything else.

bh could be better though, I agree.

-- 
Will Schenk
http://happyfuncorp.com
http://willschenk.com
http://sublimeguile.com

**Comment by rreusser** [comment]
Agreed. Really, the only thing that actually bothered me was that weird glitch where I couldn't get rid of some weird markup in the navbar. Do we remember what caused that?

**Comment by wschenk** [comment]
An exception in rendering, and then spring hanging around.  so if you kill spring it’s fine...

-- 
Will Schenk
http://happyfuncorp.com
http://willschenk.com
http://sublimeguile.com

**Comment by rreusser** [comment]
I'm willing to let this go. The new version of simple_form has been in [release candidate status](https://github.com/plataformatec/simple_form/releases) for approaching a year now, so let's keep this on the back burner and where things go.

I'll give bh a try on bootstrap components, but unless I'm unaware of config options that would fill the gap, I'll definitely use simple_form's form helpers over bh's.
