### ISSUE TITLE
CSS classes have underscores

### ISSUE THREAD

**Issue by rreusser** [HappyFunCorp/happy_seed#36]
:frowning:

**Comment by wschenk** [comment]
pull request or its not a problem.

**Comment by rreusser** [comment]
It would be good for to get in the habit of creating pull requests for this stuff. Assigned it to myself. I went nuts in github issues recently and it was surprisingly effective (much more so than jira), so in the habit of making lots of issues!

**Comment by wschenk** [comment]
Is this still a concern?
