### ISSUE TITLE
Gems that add to the asset pipeline seems to not work.

### ISSUE THREAD

**Issue by cromulus** [HappyFunCorp/happy_seed#44]
For example: in a brand new happy_seed install, adding https://github.com/icicletech/bootstrap-tokenfield-rails. 
the application.js imports the javascript file, but importing into application.css.scss fails:
```
@import 'bootstrap-tokenfield';
```
and
```
//= require 'bootstrap-tokenfield';
```
both fail.

Any idea about how to import the plugin css?

Thanks!

**Comment by wschenk** [comment]
I was able to add this.  In the Gemfile, add 

  gem 'bootstrap_tokenfield_rails'

In application.js add

  //= require bootstrap-tokenfield

In application.scss add

  @import 'bootstrap-tokenfield';

Then in an html view add:

  %input.tokenize{ type: "text" }

And in the console (or add to application.js):

  $('input.tokenize').tokenfield();

That worked for me.

**Comment by cromulus** [comment]
Ack! Yes, I see the mistake I made. Sorry to bother you!
