### ISSUE TITLE
api documentation needs updated

### ISSUE THREAD

**Issue by xABx** [HappyFunCorp/happy_seed#47]

**Comment by wschenk** [comment]
We need to make sure that the generator works, that the documentation is updated about how to use it

**Comment by meshbrain** [comment]
I am looking at it. This is my first time working with engines, so I am finding out how to test the generator.

**Comment by wschenk** [comment]
seed is structured as an application template initially, and then a number of generators that apply changes to the rails app.  There is also an engine generator, but that’s to make engines.  In doing tests then, I’d generate a sample app (test_app) and then push the specs into that.  The specs would get copied over from the generator.

-- 
Will Schenk
willschenk.com
happyfuncorp.com
sublimeguile.com

On April 15, 2016 at 12:16:27 AM, meshbrain (notifications@github.com) wrote:

I am looking at it. This is my first time working with engines, so I am finding out how to test the generator.
