### ISSUE TITLE
OAuthException for Instagram

### ISSUE THREAD

**Issue by lukemarsh** [HappyFunCorp/happy_seed#51]
I'm trying to log into my site with Instagram and i'm getting a 400 error code back.

I have created a client in my Instagram developer account:

<img width="751" alt="instagram-config" src="https://cloud.githubusercontent.com/assets/1080097/11323603/cfa84d28-910d-11e5-82f0-b464b3bb6e19.png">

I have also set my ID and secret in the .env file and restarted the server but I'm getting a 400 every time. Please help!

**Comment by wschenk** [comment]
Are you running omniauth-oauth2 1.4?  I think there's a bug in this library, I'd suggest downgrading in your Gemfile to:

  gem 'omniauth-oauth2', '1.3.1'

And see if that helps.

**Comment by lukemarsh** [comment]
I checked the Gemfile and there was no oauth2 but it was in the Gemfile.lock at 1.4.0. I changed the lock file to 1.3.1 and ran bundle install and all worked fine! The only issue is I have to use 127.0.0.1 as my redirect uri. It's probably worth adding this info to the documentation :)
