### ISSUE TITLE
Login not working in production

### ISSUE THREAD

**Issue by sushantbajra** [HappyFunCorp/happy_seed#52]
I have deployed my app in http://rsslotto.herokuapp.com/ but when I browse http://rsslotto.herokuapp.com/users/sign_in it gives me an error. I have checked the logs but there are no errors mentioned in it.

**Comment by sushantbajra** [comment]
Ok so I am very stupid. I forgot to run `heroku run rake db:migrate` and then restart the server.

**Comment by wschenk** [comment]
Glad it worked!

-- 
Will Schenk
http://happyfuncorp.com
http://willschenk.com
http://sublimeguile.com
